%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Volumes/Rohith/College/SpatioTemporalKoopman/data/BTC-USD_daily-06_02-24_04.csv
%
% Auto-generated by MATLAB on 28-May-2021 16:07:00

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Var4", "Close", "Var6", "Var7"];
opts.SelectedVariableNames = "Close";
opts.VariableTypes = ["string", "string", "string", "string", "double", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var6", "Var7"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var6", "Var7"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable("/Volumes/Rohith/College/SpatioTemporalKoopman/data/BTC-USD_daily-06_02-24_04.csv", opts);

%% Convert to output type
Close = tbl.Close;

%% Clear temporary variables
clear opts tbl