%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Volumes/Rohith/College/SpatioTemporalKoopman/SENT_DATA.csv
%
% Auto-generated by MATLAB on 28-May-2021 16:05:32

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Date", "Sent"];
opts.SelectedVariableNames = ["Date", "Sent"];
opts.VariableTypes = ["string", "datetime", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Var1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var1", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Date", "InputFormat", "yyyy-MM-dd");

% Import the data
tbl = readtable("/Volumes/Rohith/College/SpatioTemporalKoopman/SENT_DATA.csv", opts);

%% Convert to output type
Date = tbl.Date;
Sent = tbl.Sent;

%% Clear temporary variables
clear opts tbl